<form action="/dtn/employee/createPost" method="POST">
    <label for="full_name">Full Name:</label>
    <input type="text" name="full_name" id="full_name" required>

    <label for="address">Address:</label>
    <input type="text" name="address" id="address" required>

    <label for="telephone">Telephone:</label>
    <input type="text" name="telephone" id="telephone" required>

    <label for="department">Department:</label>
    <select name="department_id" id="department_id" required>
        <? foreach ($block->getDepartmentName() as $department): ?>
            <option value="<?= $department->getId() ?>"><?= $department->getName() ?></option>
        <? endforeach; ?>
    </select>

    <label for="telephone">Day of Birth:</label>
    <input type="date" name="dob" id="dob" required>

    <input type="submit" value="Insert Employee">
</form>
