<?php
$collection = $block->getEmployeesCollection();
?>
<a href="/dtn/employee/create" class="btn btn-primary">Add Employee</a>
<hr>
<table>
    <tr>
        <td>Id</td>
        <td>Full Name</td>
        <td>Address</td>
        <td>Telephone</td>
        <td>Department</td>
        <td>Action</td>
    </tr>
    <?php foreach ($collection as $employee): ?>
        <tr>
            <td><?= $employee->getId() ?></td>
            <td><?= $employee->getFullName() ?></td>
            <td><?= $employee->getAddress() ?></td>
            <td><?= $employee->getTelephone() ?></td>
            <td><?= $block->getDepartmentName($employee->getDepartmentId()) ?></td>
            <td><a href="/dtn/employee/update?id=<?= $employee->getId() ?>">Update</a></td>
            <td><a href="/dtn/employee/delete?id=<?= $employee->getId() ?>">Delete</a></td>
        </tr>
    <?php endforeach; ?>
</table>
<?= $block->getPagerHtml() ?>
