<?php
$employee = $block->getEmployee();
if ($employee->getId()):
    ?>

    <form action="/dtn/employee/updatePost" method="POST">
        <input type="hidden" name="id" id="id" value="<?= $employee->getId() ?>" required>
        <label for="full_name">Full Name:</label>
        <input type="text" name="full_name" id="full_name" value="<?= $employee->getFullName() ?>" required>

        <label for="address">Address:</label>
        <input type="text" name="address" id="address" value="<?= $employee->getAddress() ?>" required>

        <label for="telephone">Telephone:</label>
        <input type="text" name="telephone" id="telephone" value="<?= $employee->getTelephone() ?>" required>

        <label for="department">Department:</label>
        <select name="department_id" id="department_id" required>
            <? foreach ($block->getDepartmentCollection() as $department): ?>
                <option
                    value="<?= $department->getId() ?>" <?= ($department->getId() == $employee->getDepartmentId()) ? 'selected' : ''; ?> ><?= $department->getName() ?></option>
            <? endforeach; ?>
        </select>

        <label for="telephone">Day of Birth:</label>
        <input type="date" name="dob" id="dob" value="<?= $employee->getDob() ?>" required>

        <input type="submit" value="Insert Employee">
    </form>
<?php
else:
    echo $block->getErrorMessage('Employee does not exit');
endif;
?>
