<?php
$department = $block->getDepartment();
if ($department):
    ?>
    <form action="/dtn/department/editPost" method="POST">

        <input type="hidden" name="departmentId" id="" value="<?= $department->getId() ?>" required>

        <label for="full_name">Name:</label>
        <input type="text" name="name" id="" value="<?= $department->getName() ?>" required>

        <input type="submit" value="Edit Employee">
    </form>
<?php
endif;
?>
